# Generated by Django 4.2 on 2025-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
    ]
