# Generated by Django 6.0 on 2025-12-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_banner_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемые размеры: Главный баннер - 1200x400px, Малый баннер - 400x200px. Формат: JPG, PNG', null=True, upload_to='banners', verbose_name='Изображение'),
        ),
    ]
