# Generated by Django 6.0 on 2025-12-09 10:30

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_banner_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Цвет')),
                ('color_code', models.CharField(blank=True, help_text='Например: #FF0000 для красного', max_length=7, null=True, verbose_name='Код цвета (HEX)')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество на складе')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Доступен')),
                ('price_modifier', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Дополнительная стоимость для этого варианта', max_digits=12, null=True, verbose_name='Изменение цены')),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=8, max_length=50, prefix='VAR', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Варианты продуктов',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рекомендовано на маркетплейсе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Disabled', 'Disabled')], db_index=True, default='Published', max_length=50),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='content',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Контент'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category', 'price'], name='store_produ_status_2ec682_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'featured'], name='store_produ_status_0c334e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_new'], name='store_produ_status_ea99e1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'in_stock'], name='store_produ_status_6a4b82_idx'),
        ),
        migrations.AddIndex(
            model_name='variantitem',
            index=models.Index(fields=['variant', 'content'], name='store_varia_variant_49e11b_idx'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'size', 'is_available'], name='store_produ_product_1a6584_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'color', 'is_available'], name='store_produ_product_345b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_available'], name='store_produ_product_94d991_idx'),
        ),
    ]
